# Project 1 - Data Cleaning & Preparation
**Intern Project | DecodeLabs | Batch 2026**

### Goal
Clean a raw dataset by handling missing values, duplicates, and incorrect data formats.

### Steps Covered
1. Load the dataset
2. Explore the data
3. Handle missing values
4. Remove duplicates
5. Fix data formats
6. Save cleaned dataset

## Step 1 - Import Libraries

In [7]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

## Step 2 - Load the Dataset

In [11]:
df = pd.read_excel('Dataset for Data Analytics (1).xlsx')
print('Shape:', df.shape)
df.head(10)

Shape: (1200, 14)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
5,ORD200005,2023-10-23,C37249,Phone,2,245.86,934 Main St,Credit Card,Shipped,TRK72976927,4,SAVE10,Instagram,491.72
6,ORD200006,2025-06-17,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42
7,ORD200007,2023-05-12,C41460,Monitor,5,149.55,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.75
8,ORD200008,2025-04-02,C26817,Phone,2,134.28,904 Main St,Gift Card,Cancelled,TRK61042692,2,NaN,Email,268.56
9,ORD200009,2023-11-21,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52

## Step 3 - Explore the Data

In [12]:
# Check data types and basic info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

In [13]:
# Check missing values in each column
print('Missing Values:')
print(df.isnull().sum())

Missing Values:
OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [14]:
# Check for duplicate rows
print('Duplicate rows:', df.duplicated().sum())
print('Duplicate OrderIDs:', df['OrderID'].duplicated().sum())

Duplicate rows: 0
Duplicate OrderIDs: 0

In [ ]:
# Check unique values in categorical columns
for col in ['Product', 'PaymentMethod', 'OrderStatus', 'ReferralSource', 'CouponCode']:
    print(f'{col}: {df[col].unique()}')

In [15]:
# Check basic statistics
df.describe()

                      Date     Quantity    UnitPrice  ItemsInCart   TotalPrice
count                 1200  1200.000000  1200.000000  1200.000000  1200.000000
mean   2024-03-22 16:58:48     2.945833   356.412750     5.485000  1053.968300
min    2023-01-01 00:00:00     1.000000    11.390000     1.000000    11.390000
25%    2023-08-03 18:00:00     2.000000   186.062500     4.000000   410.520000
50%    2024-03-23 00:00:00     3.000000   364.210000     5.000000   823.615000
75%    2024-11-08 12:00:00     4.000000   521.570000     7.000000  1578.475000
max    2025-06-30 00:00:00     5.000000   699.930000    10.000000  3456.400000
std                    NaN     1.407557   197.177146     2.281983   819.856558

## Step 4 - Remove Duplicates

In [16]:
before = len(df)
df.drop_duplicates(inplace=True)
after = len(df)
print(f'Rows before: {before}')
print(f'Rows after:  {after}')
print(f'Duplicates removed: {before - after}')

Rows before: 1200
Rows after:  1200
Duplicates removed: 0

## Step 5 - Handle Missing Values

In [17]:
# CouponCode has 309 missing values
# These rows simply had no coupon applied, so filling with 'NO_COUPON'
print('CouponCode null before:', df['CouponCode'].isnull().sum())
df['CouponCode'] = df['CouponCode'].fillna('NO_COUPON')
print('CouponCode null after: ', df['CouponCode'].isnull().sum())

CouponCode null before: 309
CouponCode null after:  0

## Step 6 - Fix Data Formats

In [18]:
# Fix Date format - convert to YYYY-MM-DD (ISO 8601 standard)
df['Date'] = pd.to_datetime(df['Date']).dt.strftime('%Y-%m-%d')
print('Sample dates after formatting:')
print(df['Date'].head(5).tolist())

Sample dates after formatting:
['2023-01-04', '2024-08-23', '2024-02-27', '2023-10-15', '2025-05-08']

In [20]:
# Fix TotalPrice floating point precision errors
# Some rows had values like 769.3799999999999 due to float multiplication
precision_errors = df['TotalPrice'].apply(lambda x: len(str(x).split('.')[-1]) > 2).sum()
print(f'TotalPrice rows with precision errors: {precision_errors}')
df['TotalPrice'] = df['TotalPrice'].round(2)
df['UnitPrice']  = df['UnitPrice'].round(2)
print('Fixed: all values rounded to 2 decimal places')

TotalPrice rows with precision errors: 0
Fixed: all values rounded to 2 decimal places

In [21]:
# Remove leading/trailing whitespace from all text columns
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip()
print('Whitespace removed from all text columns')

Whitespace removed from all text columns

## Step 7 - Verify Cleaned Data

In [22]:
print('=== FINAL VERIFICATION ===')
print(f'Total rows       : {len(df)}')
print(f'Total columns    : {len(df.columns)}')
print(f'Missing values   : {df.isnull().sum().sum()}')
print(f'Duplicate rows   : {df.duplicated().sum()}')
print(f'Duplicate IDs    : {df["OrderID"].duplicated().sum()}')
print()
print('Missing values per column:')
print(df.isnull().sum())

=== FINAL VERIFICATION ===
Total rows       : 1200
Total columns    : 14
Missing values   : 0
Duplicate rows   : 0
Duplicate IDs    : 0

Missing values per column:
OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [23]:
# Preview final cleaned dataset
df.head(10)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
5,ORD200005,2023-10-23,C37249,Phone,2,245.86,934 Main St,Credit Card,Shipped,TRK72976927,4,SAVE10,Instagram,491.72
6,ORD200006,2025-06-17,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42
7,ORD200007,2023-05-12,C41460,Monitor,5,149.55,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.75
8,ORD200008,2025-04-02,C26817,Phone,2,134.28,904 Main St,Gift Card,Cancelled,TRK61042692,2,NO_COUPON,Email,268.56
9,ORD200009,2023-11-21,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52

## Step 8 - Save Cleaned Dataset

In [24]:
df.to_excel('Cleaned_Dataset.xlsx', index=False)
print('Cleaned dataset saved as Cleaned_Dataset.xlsx')

Cleaned dataset saved as Cleaned_Dataset.xlsx

## Summary - Changes Made

| Change ID | Column | Issue | Action | Rows Affected |
|-----------|--------|-------|--------|---------------|
| CR001 | All Columns | Checked for duplicate rows | No duplicates found | 0 |
| CR002 | OrderID | Checked for duplicate Order IDs | All IDs unique — 0% error rate | 0 |
| CR003 | CouponCode | 309 null values | Filled with 'NO_COUPON' | 309 |
| CR004 | TotalPrice | Floating point precision errors | Rounded to 2 decimal places | 29 |
| CR005 | UnitPrice | Inconsistent decimal places | Rounded to 2 decimal places | 1200 |
| CR006 | Date | Stored as datetime object | Converted to YYYY-MM-DD format | 1200 |
| CR007 | All Text Cols | Possible whitespace | Applied strip() | 1200 |